# Generated by Django 4.0.2 on 2022-02-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus_base', '0003_alter_clases_de_palabras_determinante_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clases_de_palabras',
            name='determinante_1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clases_de_palabras',
            name='determinante_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
