# Generated by Django 4.0.2 on 2022-02-25 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus_base', '0004_alter_clases_de_palabras_determinante_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casos',
            name='determinante_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus_base.determinante_1'),
        ),
        migrations.AlterField(
            model_name='casos',
            name='determinante_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus_base.determinante_2'),
        ),
        migrations.AlterField(
            model_name='casos',
            name='determinante_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus_base.determinante_3'),
        ),
    ]
