# Generated by Django 4.0.2 on 2022-05-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus_base', '0007_determinante_4_clases_de_palabras_determinante_4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='provincias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=35)),
            ],
        ),
    ]
