# Generated by Django 4.0.2 on 2022-05-19 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus_base', '0008_provincias'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='provincia',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, to='corpus_base.provincias'),
            preserve_default=False,
        ),
    ]
