# Generated by Django 4.0.2 on 2022-02-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clases_de_palabras',
            name='determinante_1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clases_de_palabras',
            name='determinante_2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clases_de_palabras',
            name='determinante_3',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
