# Generated by Django 4.0.2 on 2022-02-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus_base', '0005_alter_casos_determinante_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='fecha_incorporacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
