# Generated by Django 4.0.2 on 2022-03-02 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corpus_base', '0006_alter_documentos_fecha_incorporacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='determinante_4',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('determinante', models.CharField(max_length=45)),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='clases_de_palabras',
            name='determinante_4',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='documentos',
            name='autor',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='documentos',
            name='referencia_específica',
            field=models.CharField(default='link', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentos',
            name='revisado',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='documentos',
            name='ultima_modificacion',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='documentos',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casos',
            name='caso',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='casos',
            name='clase_de_palabra',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='corpus_base.clases_de_palabras'),
        ),
        migrations.AlterField(
            model_name='casos',
            name='desinencia',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='casos',
            name='documento',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='corpus_base.documentos'),
        ),
        migrations.AlterField(
            model_name='casos',
            name='lema',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='corpus_base.lemas'),
        ),
        migrations.AlterField(
            model_name='casos',
            name='lema_anterior',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='casos',
            name='lema_posterior',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='casos',
            name='mayuscula',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='casos',
            name='posicion',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='casos',
            name='prefijos',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='casos',
            name='determinante_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus_base.determinante_4'),
        ),
    ]
