from corpus_base.models import clases_de_palabras, determinante_1, determinante_2, determinante_3, determinante_4


def actualizar_clases():
	fila=clases_de_palabras(id=1, clase='adjetivo', determinante_1='Número', determinante_2='Género', determinante_3='Grado', determinante_4=None)
	fila.save()
	fila=clases_de_palabras(id=3, clase='artículo', determinante_1='Número', determinante_2='Género', determinante_3=None, determinante_4=None)
	fila.save()
	fila=clases_de_palabras(id=5, clase='contracción', determinante_1='Número', determinante_2=None, determinante_3=None, determinante_4=None)
	fila.save()
	fila=clases_de_palabras(id=6, clase='cuantificador', determinante_1='Número', determinante_2='Género', determinante_3='Función', determinante_4=None)
	fila.save()
	fila=clases_de_palabras(id=7, clase='demostrativo', determinante_1='Número', determinante_2='Género', determinante_3='Función', determinante_4=None)
	fila.save()
	fila=clases_de_palabras(id=8, clase='interjección', determinante_1=None, determinante_2=None, determinante_3=None, determinante_4=None)
	fila.save()
	fila=clases_de_palabras(id=9, clase='interrogativo', determinante_1='Número', determinante_2='Género', determinante_3='Función', determinante_4=None)
	fila.save()
	fila=clases_de_palabras(id=10, clase='numeral', determinante_1='Número', determinante_2='Género', determinante_3='Tipo', determinante_4=None)
	fila.save()
	fila=clases_de_palabras(id=11, clase='posesivo', determinante_1='Número', determinante_2='Género', determinante_3='Persona', determinante_4=None)
	fila.save()
	fila=clases_de_palabras(id=12, clase='preposición', determinante_1=None, determinante_2=None, determinante_3=None, determinante_4=None)
	fila.save()
	fila=clases_de_palabras(id=13, clase='pronombre', determinante_1='Número', determinante_2='Género', determinante_3='Persona', determinante_4=None)
	fila.save()
	fila=clases_de_palabras(id=14, clase='puntuación', determinante_1=None, determinante_2=None, determinante_3=None, determinante_4=None)
	fila.save()
	fila=clases_de_palabras(id=15, clase='relativo', determinante_1='Número', determinante_2='Género', determinante_3='Función', determinante_4=None)
	fila.save()
	fila=clases_de_palabras(id=16, clase='sustantivo', determinante_1='Número', determinante_2='Género', determinante_3='Tipo', determinante_4=None)
	fila.save()
	fila=clases_de_palabras(id=18, clase='extranjerismo', determinante_1=None, determinante_2=None, determinante_3=None, determinante_4=None)
	fila.save()
	fila=clases_de_palabras(id=19, clase='desconocido', determinante_1=None, determinante_2=None, determinante_3=None, determinante_4=None)
	fila.save()
	fila=clases_de_palabras(id=20, clase='afijo', determinante_1=None, determinante_2=None, determinante_3=None, determinante_4=None)
	fila.save()
	fila=clases_de_palabras(id=2, clase='adverbio', determinante_1='Tipo adverbio', determinante_2='Grado', determinante_3=None, determinante_4=None)
	fila.save()
	fila=clases_de_palabras(id=4, clase='conjunción', determinante_1='Tipo conjunción', determinante_2=None, determinante_3=None, determinante_4=None)
	fila.save()
	fila=clases_de_palabras(id=17, clase='verbo', determinante_1='Modo', determinante_2='Tiempo', determinante_3='Persona', determinante_4='Número')
	fila.save()
	fila=determinante_1(id=1, determinante='Singular', tipo='Número')
	fila.save()
	fila=determinante_1(id=2, determinante='Plural', tipo='Número')
	fila.save()
	fila=determinante_1(id=3, determinante='imperativo', tipo='Modo')
	fila.save()
	fila=determinante_1(id=4, determinante='indicativo', tipo='Modo')
	fila.save()
	fila=determinante_1(id=5, determinante='subjuntivo', tipo='Modo')
	fila.save()
	fila=determinante_1(id=6, determinante='coordinante', tipo='Tipo conjunción')
	fila.save()
	fila=determinante_1(id=7, determinante='subordinante', tipo='Tipo conjunción')
	fila.save()
	fila=determinante_1(id=8, determinante='afirmativo', tipo='Tipo adverbio')
	fila.save()
	fila=determinante_1(id=9, determinante='deíctico', tipo='Tipo adverbio')
	fila.save()
	fila=determinante_1(id=10, determinante='intensificador', tipo='Tipo adverbio')
	fila.save()
	fila=determinante_1(id=11, determinante='interrogativo', tipo='Tipo adverbio')
	fila.save()
	fila=determinante_1(id=12, determinante='negativo', tipo='Tipo adverbio')
	fila.save()
	fila=determinante_1(id=13, determinante='relativo', tipo='Tipo adverbio')
	fila.save()
	fila=determinante_2(id=1, determinante='Masculino', tipo='Género')
	fila.save()
	fila=determinante_2(id=2, determinante='Femenino', tipo='Género')
	fila.save()
	fila=determinante_2(id=3, determinante='Neutro', tipo='Género')
	fila.save()
	fila=determinante_2(id=4, determinante='comparativo', tipo='Grado')
	fila.save()
	fila=determinante_2(id=5, determinante='superlativo', tipo='Grado')
	fila.save()
	fila=determinante_2(id=6, determinante='condicional compuesto', tipo='Tiempo')
	fila.save()
	fila=determinante_2(id=7, determinante='condicional simple', tipo='Tiempo')
	fila.save()
	fila=determinante_2(id=8, determinante='futuro compuesto', tipo='Tiempo')
	fila.save()
	fila=determinante_2(id=9, determinante='futuro simple', tipo='Tiempo')
	fila.save()
	fila=determinante_2(id=10, determinante='gerundio compuesto', tipo='Tiempo')
	fila.save()
	fila=determinante_2(id=11, determinante='gerundio simple', tipo='Tiempo')
	fila.save()
	fila=determinante_2(id=12, determinante='infinito compuesto', tipo='Tiempo')
	fila.save()
	fila=determinante_2(id=14, determinante='participio de pasado', tipo='Tiempo')
	fila.save()
	fila=determinante_2(id=15, determinante='presente', tipo='Tiempo')
	fila.save()
	fila=determinante_2(id=16, determinante='pretérito anterior', tipo='Tiempo')
	fila.save()
	fila=determinante_2(id=17, determinante='pretérito imperfecto', tipo='Tiempo')
	fila.save()
	fila=determinante_2(id=18, determinante='pretérito perfecto compuesto', tipo='Tiempo')
	fila.save()
	fila=determinante_2(id=19, determinante='pretérito perfecto simple', tipo='Tiempo')
	fila.save()
	fila=determinante_2(id=20, determinante='pretérito pluscuamperfecto', tipo='Tiempo')
	fila.save()
	fila=determinante_2(id=13, determinante='infinitivo simple', tipo='Tiempo')
	fila.save()
	fila=determinante_3(id=1, determinante='primera', tipo='Persona')
	fila.save()
	fila=determinante_3(id=2, determinante='segunda', tipo='Persona')
	fila.save()
	fila=determinante_3(id=3, determinante='tercera', tipo='Persona')
	fila.save()
	fila=determinante_3(id=4, determinante='determinante', tipo='Función')
	fila.save()
	fila=determinante_3(id=5, determinante='núcleo', tipo='Función')
	fila.save()
	fila=determinante_3(id=6, determinante='cardinal', tipo='Tipo')
	fila.save()
	fila=determinante_3(id=7, determinante='ordinal', tipo='Tipo')
	fila.save()
	fila=determinante_4(id=2, determinante='Plural', tipo='Número')
	fila.save()
	fila=determinante_4(id=1, determinante='Singular', tipo='Número')
	fila.save()
