# Generated by Django 4.0.2 on 2022-03-25 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=120)),
                ('documento', models.CharField(blank=True, max_length=3500)),
                ('bibliografia', models.CharField(blank=True, max_length=500)),
                ('publicado', models.BooleanField(blank=True, default=False)),
                ('referencia', models.CharField(blank=True, max_length=200)),
                ('autor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
