# Generated by Django 4.0.2 on 2022-03-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='abstract',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='articulos',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
